# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_by', models.CharField(max_length=30)),
                ('card_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('trans_date', models.DateTimeField(blank=True, null=True)),
                ('msg_recv_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
