# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_by', models.CharField(max_length=30)),
                ('card_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('trans_date', models.DateTimeField(blank=True, null=True)),
                ('msg_recv_date', models.DateTimeField()),
            ],
        ),
    ]
