# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='msg_recv_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
